# - name: Updating system
#   ansible.builtin.shell: |
#     yum update -y
#     yum upgrade -y



- name: Install yum-utils
  ansible.builtin.yum:
    name: yum-utils
    state: present

- name: Add repository of terraform
  get_url:
    url: "{{ repo_url }}"
    dest: /usr/local/bin/
    mode: 0755 

- name: Extract foo.tgz into /var/lib/foo
  ansible.builtin.unarchive:
    src: terraform*
    dest: /usr/local/bin/
    remote_src: 


