# - name: Updating system
#   ansible.builtin.shell: |
#     yum update -y
#     yum upgrade -y



- name: Install yum-utils
  ansible.builtin.yum:
    name: yum-utils
    state: present

- name: Add repository of terraform
  ansible.builtin.yum_repository:
    name: yum-config-manager
    description: EPEL YUM repo
    baseurl: "{{repo_url}}"


- name: Install terraform from the repo
  ansible.builtin.shell: yum -y install terraform
  
