- name: Installation of elastic repo
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install Filebeat
  ansible.builtin.yum:
    name: filebeat
    state: installed

- name: Copying of filebeat.yml
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: Restart Filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    enabled: yes

- name: Copy Logstash Configuration
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Restart Logstash
  ansible.builtin.systemd:
    name: logstash
    state: restarted


- name: Create Config in Nginx
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

