- name: Include task list in play
  ansible.builtin.import_tasks:
    file: server.yml
  when: prometheus_server


- name: Include task list in play
  ansible.builtin.import_tasks:
    file: exporter.yml
  when: node_exporter