- name: Unarchive Prometheus
  ansible.builtin.unarchive:
    src: "{{ url_prometheus }}"
    dest: /opt/
    remote_src: true
    mode: '777'


- name: Copy prometheus.service file to prometheus folder
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: Copy alerts.yml file to prometheus folder
  ansible.builtin.template:
    src: alerts.yml
    dest: /opt/{{prometheus_dir}}/alerts.yml

- name: Copy prometheus.yml file to prometheus folder
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/{{prometheus_dir}}/prometheus.yml

- name: Prometheus server start
  ansible.builtin.service:
    name: prometheus
    state: restarted
    daemon_reload: true
