- name: Creation of prometheus folder in /opt
  ansible.builtin.shell: |
    cd /opt
    mkdir prometheus

- name: Template a file to prometheus folder
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Prometheus server start
  ansible.builtin.service:
    name: prometheus
    state: restarted

- name: Check Prometheus is started
  ansible.builtin.shell: netstat -lntp | grep 9090