- name: Creation of prometheus folder in /opt
  ansible.builtin.shell: |
    cd /opt
    mkdir prometheus
    touch prometheus.service


- name: Download foo.conf
  ansible.builtin.get_url:
    url: "{{ url_prometheus }}"
    dest: ~/
    mode: '777'

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: ~/prometheus-2.43.0.linux-amd64.tar.gz
    dest: /opt/prometheus
    remote_src: no

- name: Copy prometheus.service file to prometheus folder
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: Prometheus server start
  ansible.builtin.service:
    name: prometheus
    state: started

- name: Copy prometheus.yml file to prometheus folder
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Prometheus server start
  ansible.builtin.service:
    name: prometheus
    state: restarted

- name: Check Prometheus is started
  ansible.builtin.shell: ps -ef | grep /prometheus