- name: Unarchive Prometheus
  ansible.builtin.unarchive:
    src: "{{ url_prometheus }}"
    dest: /opt/
    remote_src: true
    mode: '777'

- name: Renaming the folders
  ansible.builtin.shell: |
    mv /opt/prometheus* /opt/prometheus

- name: Copy prometheus.service file to prometheus folder
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: Copy prometheus.yml file to prometheus folder
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus*/prometheus.yml

- name: Prometheus server start
  ansible.builtin.service:
    name: prometheus
    state: restarted
    daemon_reload: true
