prometheus_server: true
node_exporter: true
url_prometheus: https://github.com/prometheus/prometheus/releases/download/v2.43.0/prometheus-2.43.0.linux-amd64.tar.gz
exporter_url: https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
exporter_dir: "{{ exporter_url |  split('/') | last | regex_replace('.tar.gz', '')}}"
prometheus_dir: "{{ url_prometheus |  split('/') | last | regex_replace('.tar.gz', '')}}"