groups:
- name: example
  rules:
  - alert: HighRequestLatency
    expr: up < 1
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: High request latency

- name: example
  rules:
  - alert: CPU Usage
    expr: up < 1
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: High request latency